ai_questions = [
    "What are ecosystem services?",
    "How does fire affect ecology?",
    "What is climate change?",
    "Why does conservation matter?",
    "How to classify ecosystems?",
    "What affects water cycles?",
    "Role of forests in ecology?",
    "How do animals interact?",
    "What is species invasion?",
    "Human impact on ecology.",
    "How does temperature vary season?",
    "Why conserve natural habitats?",
    "Effect of pollution on plants?",
    "Best practices in conservation.",
    "What threatened species lists?",
    "Impact of human migration.",
    "Ecological role of fungi.",
    "Deserts as ecosystems models?",
    "Eco impacts of recreation?",
    "What is a biome?",
    "Types of ecological diversity.",
    "Importance of wetland areas.",
    "Atmosphere role in ecosystems?",
    "Weathering vs erosion process?",
    "Significance of soil layers.",
    "What are wildlife corridors?",
    "Impact of dams ecosystems?",
    "What causes disease outbreaks?",
    "Types of natural disasters.",
    "Urbanization and ecology relationship?",
    "Photosynthesis within coral?",
    "Genetics applied conservation targets"
    ]

eco_tips = [
    ["Reduce, Reuse, Recycle", "Follow the classic mantra: reduce your consumption, reuse items whenever possible, and recycle what you can't reuse."],
    ["Conserve Water", "Take shorter showers, fix leaky faucets, and water your lawn efficiently."],
    ["Switch to LED lights", "LED bulbs use significantly less energy and last longer than traditional incandescent bulbs."],
    ["Use Public Transportation", "Opt for buses, trains, or carpools to reduce your carbon footprint."],
    ["Walk or Bike", "Choose active transportation for shorter distances, improving your health and the environment."],
    ["Choose Reusable Bags", "Bring your own bags when shopping to avoid single-use plastic bags."],
    ["Avoid Bottled Water", "Use a reusable water bottle and fill it with tap water."],
    ["Eat Less Meat", "Animal agriculture has a significant environmental impact, consider reducing your meat consumption."],
    ["Compost Food Scraps", "Compost organic waste to create nutrient-rich soil and reduce landfill waste."],
    ["Plant Trees", "Trees absorb carbon dioxide and provide numerous other environmental benefits."],
    ["Buy Local", "Support local farmers and businesses to reduce transportation emissions."],
    ["Choose Sustainable Products", "Look for products made from recycled materials or sustainably sourced ingredients."],
    ["Avoid Unnecessary Packaging", "Choose products with minimal packaging or opt for bulk options."],
    ["Turn Off Lights", "Remember to turn off lights when you leave a room."],
    ["Unplug Electronics", "Unplug devices when not in use to prevent standby power consumption."],
    ["Use Energy-Efficient Appliances", "Invest in energy-star certified appliances for lower energy bills."],
    ["Insulate Your Home", "Proper insulation can significantly reduce heating and cooling costs."],
    ["Use Natural Cleaning Products", "Choose eco-friendly cleaning products to avoid harsh chemicals."],
    ["Recycle Paper Properly", "Ensure paper is clean and free of plastic or food residue before recycling."],
    ["Support Environmental Organizations", "Donate to or volunteer with organizations working to protect the environment."],
    ["Educate Yourself", "Stay informed about environmental issues and solutions."],
    ["Reduce Food Waste", "Plan meals carefully, store food properly, and compost leftovers."],
    ["Choose Sustainable Seafood", "Select seafood that is sustainably harvested to protect ocean ecosystems."],
    ["Use a Programmable Thermostat", "Optimize your heating and cooling schedule to save energy."],
    ["Line Dry Clothes", "Air-dry your laundry instead of using a dryer to conserve energy."],
    ["Take Shorter Flights", "Reduce your air travel miles by choosing shorter flights or alternate transportation."],
    ["Avoid Single-Use Plastics", "Say no to straws, cutlery, and other disposable plastic items."],
    ["Donate or Sell Unwanted Items", "Give unwanted items a second life instead of throwing them away."],
    ["Shop Secondhand", "Consider buying used clothing, furniture, or electronics to reduce consumption."],
    ["Make Your Own Gifts", "Create personalized gifts using eco-friendly materials."],
    ["Use a Reusable Coffee Cup", "Skip disposable coffee cups and bring your own reusable cup."],
    ["Support Renewable Energy", "Choose electricity providers that offer renewable energy options."],
    ["Reduce Noise Pollution", "Be mindful of loud noises and use noise-reducing devices when possible."],
    ["Protect Biodiversity", "Support habitat conservation and choose products that don't harm wildlife."],
    ["Conserve Soil", "Avoid over-fertilizing and practice soil erosion control measures."],
    ["Reduce Chemical Use", "Opt for natural pest control methods and reduce your use of harmful chemicals."],
    ["Advocate for Change", "Speak out about environmental issues and support policies that protect the planet."],
    ["Be a Conscious Consumer", "Make informed choices about the products you buy and their environmental impact."],
    ["Spread Awareness", "Share your eco-friendly tips with friends and family to inspire others."],
    ["Embrace Minimalism", "Live with less and focus on experiences rather than material possessions."],
    ["Practice Gratitude", "Appreciate the Earth's resources and be thankful for what we have."]]

globals = {
    'debug': False,
    'Ai_questions': ai_questions,
    'Eco_tips': eco_tips
    
    
    }